//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageAdmin
    {
        public string SupportPhone { get; set; }
        public string SupportEmail { get; set; }
        public byte[] EmailId { get; set; }
        public string DisplayPic { get; set; }
        public string ProfilePicture { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
