//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MembersData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MembersData()
        {
            this.Buyers = new HashSet<Buyer>();
            this.NoteDetails = new HashSet<NoteDetail>();
            this.Sellers = new HashSet<Seller>();
            this.Date = DateTime.Now;
            this.IsDetailsSubmitted = false;
            this.IsEmailVerified = false;
            this.IsActive = true;
        }
    
        public int Id { get; set; }
        public string ProfilePicture { get; set; }
        [DisplayName("First Name*")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please Enter the FirstName")]
        public string FirstName { get; set; }
        [DisplayName("Last Name*")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please Enter the LastName")]
        public string LastName { get; set; }
        [DisplayName("Email Id*")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please Enter the EmailId")]

        public string EmailId { get; set; }
        [DisplayName("Password*")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter the Password")]
        public string Password { get; set; }
        [DisplayName("Password*")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter the Password")]

        public string CPassword { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string PhoneNo { get; set; }
        public string AddLine1 { get; set; }
        public string Addline2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string University { get; set; }
        public string Collage { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public bool IsEmailVerified { get; set; }
        public bool IsDetailsSubmitted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buyer> Buyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteDetail> NoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller> Sellers { get; set; }
    }
}
