//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string InaAppropriate { get; set; }
        public int NoteId { get; set; }
        public int BuyerId { get; set; }
    
        public virtual NoteDetail NoteDetail { get; set; }
    }
}
